=begin
#MailOdds Email Validation API

#MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

The version of the OpenAPI document: 1.0.0
Contact: support@mailodds.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Mailodds::SendingDomainsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SendingDomainsApi' do
  before do
    # run before each test
    @api_instance = Mailodds::SendingDomainsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SendingDomainsApi' do
    it 'should create an instance of SendingDomainsApi' do
      expect(@api_instance).to be_instance_of(Mailodds::SendingDomainsApi)
    end
  end

  # unit tests for create_sending_domain
  # Add a sending domain
  # Register a new sending domain with NS delegation. After adding, configure DNS records and verify.
  # @param create_sending_domain_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateSendingDomain201Response]
  describe 'create_sending_domain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_sending_domain
  # Delete a sending domain
  # Permanently remove a sending domain from the account.
  # @param domain_id 
  # @param [Hash] opts the optional parameters
  # @return [DeletePolicyRule200Response]
  describe 'delete_sending_domain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sending_domain
  # Get a sending domain
  # Get details of a specific sending domain including DNS verification status.
  # @param domain_id 
  # @param [Hash] opts the optional parameters
  # @return [CreateSendingDomain201Response]
  describe 'get_sending_domain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sending_domain_identity_score
  # Get domain identity score
  # Get a composite DNS health score for the sending domain, checking DKIM, SPF, DMARC, MX, and return path configuration.
  # @param domain_id 
  # @param [Hash] opts the optional parameters
  # @return [GetSendingDomainIdentityScore200Response]
  describe 'get_sending_domain_identity_score test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sending_stats
  # Get sending statistics
  # Get aggregate sending statistics across all domains for the account, including delivery rates, open rates, and click rates.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :period Time period
  # @option opts [String] :domain_id Filter by domain
  # @return [GetSendingStats200Response]
  describe 'get_sending_stats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_sending_domains
  # List sending domains
  # List all sending domains for the authenticated account.
  # @param [Hash] opts the optional parameters
  # @return [ListSendingDomains200Response]
  describe 'list_sending_domains test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for verify_sending_domain
  # Verify domain DNS records
  # Check and verify all DNS records (DKIM, SPF, DMARC, MX, return path) for the sending domain.
  # @param domain_id 
  # @param [Hash] opts the optional parameters
  # @return [CreateSendingDomain201Response]
  describe 'verify_sending_domain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
