=begin
#MailOdds Email Validation API

#MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

The version of the OpenAPI document: 1.0.0
Contact: support@mailodds.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Mailodds::SuppressionListsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SuppressionListsApi' do
  before do
    # run before each test
    @api_instance = Mailodds::SuppressionListsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SuppressionListsApi' do
    it 'should create an instance of SuppressionListsApi' do
      expect(@api_instance).to be_instance_of(Mailodds::SuppressionListsApi)
    end
  end

  # unit tests for add_suppression
  # Add suppression entries
  # Add emails or domains to the suppression list.
  # @param add_suppression_request 
  # @param [Hash] opts the optional parameters
  # @return [AddSuppressionResponse]
  describe 'add_suppression test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for check_suppression
  # Check suppression status
  # Check if an email is suppressed.
  # @param check_suppression_request 
  # @param [Hash] opts the optional parameters
  # @return [SuppressionCheckResponse]
  describe 'check_suppression test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_suppression_stats
  # Get suppression statistics
  # Get statistics about the suppression list.
  # @param [Hash] opts the optional parameters
  # @return [SuppressionStatsResponse]
  describe 'get_suppression_stats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_suppression
  # List suppression entries
  # List all suppression entries for the account.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :type 
  # @option opts [String] :search 
  # @return [SuppressionListResponse]
  describe 'list_suppression test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_suppression
  # Remove suppression entries
  # Remove emails or domains from the suppression list.
  # @param remove_suppression_request 
  # @param [Hash] opts the optional parameters
  # @return [RemoveSuppression200Response]
  describe 'remove_suppression test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
