=begin
#MailOdds Email Validation API

#MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

The version of the OpenAPI document: 1.0.0
Contact: support@mailodds.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Mailodds::SystemApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SystemApi' do
  before do
    # run before each test
    @api_instance = Mailodds::SystemApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SystemApi' do
    it 'should create an instance of SystemApi' do
      expect(@api_instance).to be_instance_of(Mailodds::SystemApi)
    end
  end

  # unit tests for get_telemetry_summary
  # Get validation telemetry
  # Get validation metrics for your account. Useful for building dashboards and monitoring. Supports ETag caching.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :window Time window for metrics
  # @return [TelemetrySummary]
  describe 'get_telemetry_summary test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for health_check
  # Health check
  # Check API health status. No authentication required.
  # @param [Hash] opts the optional parameters
  # @return [HealthCheck200Response]
  describe 'health_check test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
