=begin
#MailOdds Email Validation API

#MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

The version of the OpenAPI document: 1.0.0
Contact: support@mailodds.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

# Common files
require 'mailodds/api_client'
require 'mailodds/api_error'
require 'mailodds/api_model_base'
require 'mailodds/version'
require 'mailodds/configuration'

# Models
require 'mailodds/models/add_policy_rule201_response'
require 'mailodds/models/add_suppression_request'
require 'mailodds/models/add_suppression_request_entries_inner'
require 'mailodds/models/add_suppression_response'
require 'mailodds/models/check_suppression_request'
require 'mailodds/models/create_job_from_s3_request'
require 'mailodds/models/create_job_request'
require 'mailodds/models/create_policy_from_preset_request'
require 'mailodds/models/create_policy_request'
require 'mailodds/models/delete_job200_response'
require 'mailodds/models/delete_policy200_response'
require 'mailodds/models/delete_policy_rule200_response'
require 'mailodds/models/error_response'
require 'mailodds/models/get_presigned_upload_request'
require 'mailodds/models/health_check200_response'
require 'mailodds/models/job'
require 'mailodds/models/job_list_response'
require 'mailodds/models/job_response'
require 'mailodds/models/job_summary'
require 'mailodds/models/pagination'
require 'mailodds/models/policy'
require 'mailodds/models/policy_list_response'
require 'mailodds/models/policy_list_response_limits'
require 'mailodds/models/policy_presets_response'
require 'mailodds/models/policy_presets_response_presets_inner'
require 'mailodds/models/policy_response'
require 'mailodds/models/policy_rule'
require 'mailodds/models/policy_rule_action'
require 'mailodds/models/policy_test_response'
require 'mailodds/models/presigned_upload_response'
require 'mailodds/models/presigned_upload_response_upload'
require 'mailodds/models/remove_suppression200_response'
require 'mailodds/models/remove_suppression_request'
require 'mailodds/models/results_response'
require 'mailodds/models/suppression_check_response'
require 'mailodds/models/suppression_entry'
require 'mailodds/models/suppression_list_response'
require 'mailodds/models/suppression_stats_response'
require 'mailodds/models/suppression_stats_response_by_type'
require 'mailodds/models/telemetry_summary'
require 'mailodds/models/telemetry_summary_rates'
require 'mailodds/models/telemetry_summary_top_domains_inner'
require 'mailodds/models/telemetry_summary_top_reasons_inner'
require 'mailodds/models/telemetry_summary_totals'
require 'mailodds/models/test_policy_request'
require 'mailodds/models/test_policy_request_test_result'
require 'mailodds/models/update_policy_request'
require 'mailodds/models/validate_request'
require 'mailodds/models/validation_response'
require 'mailodds/models/validation_response_suppression_match'
require 'mailodds/models/validation_result'

# APIs
require 'mailodds/api/bulk_validation_api'
require 'mailodds/api/email_validation_api'
require 'mailodds/api/suppression_lists_api'
require 'mailodds/api/system_api'
require 'mailodds/api/validation_policies_api'

module Mailodds
  class << self
    # Customize default settings for the SDK using block.
    #   Mailodds.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
