=begin
#MailOdds Email Validation API

#MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

The version of the OpenAPI document: 1.0.0
Contact: support@mailodds.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Mailodds
  # Same fields as DeliverRequest but 'to' accepts up to 100 recipients.
  class BatchDeliverRequest < ApiModelBase
    # List of recipient email addresses (max 100)
    attr_accessor :to

    attr_accessor :from

    attr_accessor :subject

    attr_accessor :html

    attr_accessor :text

    attr_accessor :domain_id

    attr_accessor :reply_to

    attr_accessor :headers

    attr_accessor :tags

    attr_accessor :campaign_type

    attr_accessor :structured_data

    attr_accessor :options

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'to' => :'to',
        :'from' => :'from',
        :'subject' => :'subject',
        :'html' => :'html',
        :'text' => :'text',
        :'domain_id' => :'domain_id',
        :'reply_to' => :'reply_to',
        :'headers' => :'headers',
        :'tags' => :'tags',
        :'campaign_type' => :'campaign_type',
        :'structured_data' => :'structured_data',
        :'options' => :'options'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'to' => :'Array<String>',
        :'from' => :'String',
        :'subject' => :'String',
        :'html' => :'String',
        :'text' => :'String',
        :'domain_id' => :'String',
        :'reply_to' => :'String',
        :'headers' => :'Object',
        :'tags' => :'Array<String>',
        :'campaign_type' => :'String',
        :'structured_data' => :'BatchDeliverRequestStructuredData',
        :'options' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Mailodds::BatchDeliverRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Mailodds::BatchDeliverRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'to')
        if (value = attributes[:'to']).is_a?(Array)
          self.to = value
        end
      else
        self.to = nil
      end

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      else
        self.from = nil
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      else
        self.subject = nil
      end

      if attributes.key?(:'html')
        self.html = attributes[:'html']
      end

      if attributes.key?(:'text')
        self.text = attributes[:'text']
      end

      if attributes.key?(:'domain_id')
        self.domain_id = attributes[:'domain_id']
      else
        self.domain_id = nil
      end

      if attributes.key?(:'reply_to')
        self.reply_to = attributes[:'reply_to']
      end

      if attributes.key?(:'headers')
        self.headers = attributes[:'headers']
      end

      if attributes.key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end

      if attributes.key?(:'campaign_type')
        self.campaign_type = attributes[:'campaign_type']
      end

      if attributes.key?(:'structured_data')
        self.structured_data = attributes[:'structured_data']
      end

      if attributes.key?(:'options')
        self.options = attributes[:'options']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @to.nil?
        invalid_properties.push('invalid value for "to", to cannot be nil.')
      end

      if @to.length > 100
        invalid_properties.push('invalid value for "to", number of items must be less than or equal to 100.')
      end

      if @from.nil?
        invalid_properties.push('invalid value for "from", from cannot be nil.')
      end

      if @subject.nil?
        invalid_properties.push('invalid value for "subject", subject cannot be nil.')
      end

      if @domain_id.nil?
        invalid_properties.push('invalid value for "domain_id", domain_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @to.nil?
      return false if @to.length > 100
      return false if @from.nil?
      return false if @subject.nil?
      return false if @domain_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] to Value to be assigned
    def to=(to)
      if to.nil?
        fail ArgumentError, 'to cannot be nil'
      end

      if to.length > 100
        fail ArgumentError, 'invalid value for "to", number of items must be less than or equal to 100.'
      end

      @to = to
    end

    # Custom attribute writer method with validation
    # @param [Object] from Value to be assigned
    def from=(from)
      if from.nil?
        fail ArgumentError, 'from cannot be nil'
      end

      @from = from
    end

    # Custom attribute writer method with validation
    # @param [Object] subject Value to be assigned
    def subject=(subject)
      if subject.nil?
        fail ArgumentError, 'subject cannot be nil'
      end

      @subject = subject
    end

    # Custom attribute writer method with validation
    # @param [Object] domain_id Value to be assigned
    def domain_id=(domain_id)
      if domain_id.nil?
        fail ArgumentError, 'domain_id cannot be nil'
      end

      @domain_id = domain_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          to == o.to &&
          from == o.from &&
          subject == o.subject &&
          html == o.html &&
          text == o.text &&
          domain_id == o.domain_id &&
          reply_to == o.reply_to &&
          headers == o.headers &&
          tags == o.tags &&
          campaign_type == o.campaign_type &&
          structured_data == o.structured_data &&
          options == o.options
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [to, from, subject, html, text, domain_id, reply_to, headers, tags, campaign_type, structured_data, options].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
