=begin
#MailOdds Email Validation API

#MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

The version of the OpenAPI document: 1.0.0
Contact: support@mailodds.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Mailodds
  class GetSendingStats200ResponseStats < ApiModelBase
    attr_accessor :period

    attr_accessor :sent

    attr_accessor :delivered

    attr_accessor :bounced

    attr_accessor :deferred

    attr_accessor :failed

    attr_accessor :opened_total

    attr_accessor :opened_unique

    attr_accessor :clicked_total

    attr_accessor :clicked_unique

    attr_accessor :unsubscribed

    attr_accessor :delivery_rate

    attr_accessor :open_rate

    attr_accessor :click_rate

    # Opens from known bots/scanners
    attr_accessor :bot_opens

    # Verified human opens
    attr_accessor :human_opens

    # Percentage of opens from bots
    attr_accessor :bot_open_pct

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'period' => :'period',
        :'sent' => :'sent',
        :'delivered' => :'delivered',
        :'bounced' => :'bounced',
        :'deferred' => :'deferred',
        :'failed' => :'failed',
        :'opened_total' => :'opened_total',
        :'opened_unique' => :'opened_unique',
        :'clicked_total' => :'clicked_total',
        :'clicked_unique' => :'clicked_unique',
        :'unsubscribed' => :'unsubscribed',
        :'delivery_rate' => :'delivery_rate',
        :'open_rate' => :'open_rate',
        :'click_rate' => :'click_rate',
        :'bot_opens' => :'bot_opens',
        :'human_opens' => :'human_opens',
        :'bot_open_pct' => :'bot_open_pct'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'period' => :'String',
        :'sent' => :'Integer',
        :'delivered' => :'Integer',
        :'bounced' => :'Integer',
        :'deferred' => :'Integer',
        :'failed' => :'Integer',
        :'opened_total' => :'Integer',
        :'opened_unique' => :'Integer',
        :'clicked_total' => :'Integer',
        :'clicked_unique' => :'Integer',
        :'unsubscribed' => :'Integer',
        :'delivery_rate' => :'Float',
        :'open_rate' => :'Float',
        :'click_rate' => :'Float',
        :'bot_opens' => :'Integer',
        :'human_opens' => :'Integer',
        :'bot_open_pct' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Mailodds::GetSendingStats200ResponseStats` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Mailodds::GetSendingStats200ResponseStats`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'period')
        self.period = attributes[:'period']
      end

      if attributes.key?(:'sent')
        self.sent = attributes[:'sent']
      end

      if attributes.key?(:'delivered')
        self.delivered = attributes[:'delivered']
      end

      if attributes.key?(:'bounced')
        self.bounced = attributes[:'bounced']
      end

      if attributes.key?(:'deferred')
        self.deferred = attributes[:'deferred']
      end

      if attributes.key?(:'failed')
        self.failed = attributes[:'failed']
      end

      if attributes.key?(:'opened_total')
        self.opened_total = attributes[:'opened_total']
      end

      if attributes.key?(:'opened_unique')
        self.opened_unique = attributes[:'opened_unique']
      end

      if attributes.key?(:'clicked_total')
        self.clicked_total = attributes[:'clicked_total']
      end

      if attributes.key?(:'clicked_unique')
        self.clicked_unique = attributes[:'clicked_unique']
      end

      if attributes.key?(:'unsubscribed')
        self.unsubscribed = attributes[:'unsubscribed']
      end

      if attributes.key?(:'delivery_rate')
        self.delivery_rate = attributes[:'delivery_rate']
      end

      if attributes.key?(:'open_rate')
        self.open_rate = attributes[:'open_rate']
      end

      if attributes.key?(:'click_rate')
        self.click_rate = attributes[:'click_rate']
      end

      if attributes.key?(:'bot_opens')
        self.bot_opens = attributes[:'bot_opens']
      end

      if attributes.key?(:'human_opens')
        self.human_opens = attributes[:'human_opens']
      end

      if attributes.key?(:'bot_open_pct')
        self.bot_open_pct = attributes[:'bot_open_pct']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          period == o.period &&
          sent == o.sent &&
          delivered == o.delivered &&
          bounced == o.bounced &&
          deferred == o.deferred &&
          failed == o.failed &&
          opened_total == o.opened_total &&
          opened_unique == o.opened_unique &&
          clicked_total == o.clicked_total &&
          clicked_unique == o.clicked_unique &&
          unsubscribed == o.unsubscribed &&
          delivery_rate == o.delivery_rate &&
          open_rate == o.open_rate &&
          click_rate == o.click_rate &&
          bot_opens == o.bot_opens &&
          human_opens == o.human_opens &&
          bot_open_pct == o.bot_open_pct
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [period, sent, delivered, bounced, deferred, failed, opened_total, opened_unique, clicked_total, clicked_unique, unsubscribed, delivery_rate, open_rate, click_rate, bot_opens, human_opens, bot_open_pct].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
