=begin
#MailOdds Email Validation API

#MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

The version of the OpenAPI document: 1.0.0
Contact: support@mailodds.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Mailodds
  class Subscriber < ApiModelBase
    # Subscriber UUID
    attr_accessor :id

    # List UUID
    attr_accessor :list_id

    attr_accessor :email

    attr_accessor :name

    attr_accessor :status

    # IP address of subscription
    attr_accessor :consent_source_ip

    # Page URL where form was submitted
    attr_accessor :consent_page_url

    # Form identifier
    attr_accessor :consent_form_id

    attr_accessor :consent_timestamp

    attr_accessor :confirmed_at

    attr_accessor :unsubscribed_at

    # Email validation result
    attr_accessor :validation_result

    # Custom metadata
    attr_accessor :metadata

    attr_accessor :created_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'list_id' => :'list_id',
        :'email' => :'email',
        :'name' => :'name',
        :'status' => :'status',
        :'consent_source_ip' => :'consent_source_ip',
        :'consent_page_url' => :'consent_page_url',
        :'consent_form_id' => :'consent_form_id',
        :'consent_timestamp' => :'consent_timestamp',
        :'confirmed_at' => :'confirmed_at',
        :'unsubscribed_at' => :'unsubscribed_at',
        :'validation_result' => :'validation_result',
        :'metadata' => :'metadata',
        :'created_at' => :'created_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'list_id' => :'String',
        :'email' => :'String',
        :'name' => :'String',
        :'status' => :'String',
        :'consent_source_ip' => :'String',
        :'consent_page_url' => :'String',
        :'consent_form_id' => :'String',
        :'consent_timestamp' => :'Time',
        :'confirmed_at' => :'Time',
        :'unsubscribed_at' => :'Time',
        :'validation_result' => :'Object',
        :'metadata' => :'Object',
        :'created_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'name',
        :'consent_source_ip',
        :'consent_page_url',
        :'consent_form_id',
        :'consent_timestamp',
        :'confirmed_at',
        :'unsubscribed_at',
        :'validation_result',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Mailodds::Subscriber` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Mailodds::Subscriber`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'list_id')
        self.list_id = attributes[:'list_id']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'consent_source_ip')
        self.consent_source_ip = attributes[:'consent_source_ip']
      end

      if attributes.key?(:'consent_page_url')
        self.consent_page_url = attributes[:'consent_page_url']
      end

      if attributes.key?(:'consent_form_id')
        self.consent_form_id = attributes[:'consent_form_id']
      end

      if attributes.key?(:'consent_timestamp')
        self.consent_timestamp = attributes[:'consent_timestamp']
      end

      if attributes.key?(:'confirmed_at')
        self.confirmed_at = attributes[:'confirmed_at']
      end

      if attributes.key?(:'unsubscribed_at')
        self.unsubscribed_at = attributes[:'unsubscribed_at']
      end

      if attributes.key?(:'validation_result')
        self.validation_result = attributes[:'validation_result']
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      status_validator = EnumAttributeValidator.new('String', ["pending", "confirmed", "unsubscribed", "bounced"])
      return false unless status_validator.valid?(@status)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["pending", "confirmed", "unsubscribed", "bounced"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          list_id == o.list_id &&
          email == o.email &&
          name == o.name &&
          status == o.status &&
          consent_source_ip == o.consent_source_ip &&
          consent_page_url == o.consent_page_url &&
          consent_form_id == o.consent_form_id &&
          consent_timestamp == o.consent_timestamp &&
          confirmed_at == o.confirmed_at &&
          unsubscribed_at == o.unsubscribed_at &&
          validation_result == o.validation_result &&
          metadata == o.metadata &&
          created_at == o.created_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, list_id, email, name, status, consent_source_ip, consent_page_url, consent_form_id, consent_timestamp, confirmed_at, unsubscribed_at, validation_result, metadata, created_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
