=begin
#MailOdds Email Validation API

#MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

The version of the OpenAPI document: 1.0.0
Contact: support@mailodds.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Mailodds
  # Validation metrics for building dashboards and monitoring.
  class TelemetrySummary < ApiModelBase
    attr_accessor :schema_version

    attr_accessor :window

    attr_accessor :generated_at

    attr_accessor :timezone

    attr_accessor :totals

    attr_accessor :rates

    # Top rejection/status reasons
    attr_accessor :top_reasons

    # Top domains by volume
    attr_accessor :top_domains

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'schema_version' => :'schemaVersion',
        :'window' => :'window',
        :'generated_at' => :'generatedAt',
        :'timezone' => :'timezone',
        :'totals' => :'totals',
        :'rates' => :'rates',
        :'top_reasons' => :'topReasons',
        :'top_domains' => :'topDomains'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'schema_version' => :'String',
        :'window' => :'String',
        :'generated_at' => :'Time',
        :'timezone' => :'String',
        :'totals' => :'TelemetrySummaryTotals',
        :'rates' => :'TelemetrySummaryRates',
        :'top_reasons' => :'Array<TelemetrySummaryTopReasonsInner>',
        :'top_domains' => :'Array<TelemetrySummaryTopDomainsInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Mailodds::TelemetrySummary` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Mailodds::TelemetrySummary`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'schema_version')
        self.schema_version = attributes[:'schema_version']
      end

      if attributes.key?(:'window')
        self.window = attributes[:'window']
      end

      if attributes.key?(:'generated_at')
        self.generated_at = attributes[:'generated_at']
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      end

      if attributes.key?(:'totals')
        self.totals = attributes[:'totals']
      end

      if attributes.key?(:'rates')
        self.rates = attributes[:'rates']
      end

      if attributes.key?(:'top_reasons')
        if (value = attributes[:'top_reasons']).is_a?(Array)
          self.top_reasons = value
        end
      end

      if attributes.key?(:'top_domains')
        if (value = attributes[:'top_domains']).is_a?(Array)
          self.top_domains = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      window_validator = EnumAttributeValidator.new('String', ["1h", "24h", "30d"])
      return false unless window_validator.valid?(@window)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] window Object to be assigned
    def window=(window)
      validator = EnumAttributeValidator.new('String', ["1h", "24h", "30d"])
      unless validator.valid?(window)
        fail ArgumentError, "invalid value for \"window\", must be one of #{validator.allowable_values}."
      end
      @window = window
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          schema_version == o.schema_version &&
          window == o.window &&
          generated_at == o.generated_at &&
          timezone == o.timezone &&
          totals == o.totals &&
          rates == o.rates &&
          top_reasons == o.top_reasons &&
          top_domains == o.top_domains
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [schema_version, window, generated_at, timezone, totals, rates, top_reasons, top_domains].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
