=begin
#MailOdds Email Validation API

#MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

The version of the OpenAPI document: 1.0.0
Contact: support@mailodds.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Mailodds
  class ValidationResponse < ApiModelBase
    attr_accessor :schema_version

    attr_accessor :email

    # Validation status
    attr_accessor :status

    # Detailed status reason
    attr_accessor :sub_status

    # Recommended action
    attr_accessor :action

    attr_accessor :domain

    attr_accessor :mx_found

    attr_accessor :smtp_check

    attr_accessor :disposable

    attr_accessor :role_account

    attr_accessor :free_provider

    attr_accessor :suppression_match

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'schema_version' => :'schema_version',
        :'email' => :'email',
        :'status' => :'status',
        :'sub_status' => :'sub_status',
        :'action' => :'action',
        :'domain' => :'domain',
        :'mx_found' => :'mx_found',
        :'smtp_check' => :'smtp_check',
        :'disposable' => :'disposable',
        :'role_account' => :'role_account',
        :'free_provider' => :'free_provider',
        :'suppression_match' => :'suppression_match'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'schema_version' => :'String',
        :'email' => :'String',
        :'status' => :'String',
        :'sub_status' => :'String',
        :'action' => :'String',
        :'domain' => :'String',
        :'mx_found' => :'Boolean',
        :'smtp_check' => :'Boolean',
        :'disposable' => :'Boolean',
        :'role_account' => :'Boolean',
        :'free_provider' => :'Boolean',
        :'suppression_match' => :'ValidationResponseSuppressionMatch'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Mailodds::ValidationResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Mailodds::ValidationResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'schema_version')
        self.schema_version = attributes[:'schema_version']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'sub_status')
        self.sub_status = attributes[:'sub_status']
      end

      if attributes.key?(:'action')
        self.action = attributes[:'action']
      else
        self.action = nil
      end

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      end

      if attributes.key?(:'mx_found')
        self.mx_found = attributes[:'mx_found']
      end

      if attributes.key?(:'smtp_check')
        self.smtp_check = attributes[:'smtp_check']
      end

      if attributes.key?(:'disposable')
        self.disposable = attributes[:'disposable']
      end

      if attributes.key?(:'role_account')
        self.role_account = attributes[:'role_account']
      end

      if attributes.key?(:'free_provider')
        self.free_provider = attributes[:'free_provider']
      end

      if attributes.key?(:'suppression_match')
        self.suppression_match = attributes[:'suppression_match']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @action.nil?
        invalid_properties.push('invalid value for "action", action cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @email.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["valid", "invalid", "catch_all", "do_not_mail", "unknown"])
      return false unless status_validator.valid?(@status)
      return false if @action.nil?
      action_validator = EnumAttributeValidator.new('String', ["accept", "accept_with_caution", "reject", "retry_later"])
      return false unless action_validator.valid?(@action)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.nil?
        fail ArgumentError, 'email cannot be nil'
      end

      @email = email
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["valid", "invalid", "catch_all", "do_not_mail", "unknown"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] action Object to be assigned
    def action=(action)
      validator = EnumAttributeValidator.new('String', ["accept", "accept_with_caution", "reject", "retry_later"])
      unless validator.valid?(action)
        fail ArgumentError, "invalid value for \"action\", must be one of #{validator.allowable_values}."
      end
      @action = action
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          schema_version == o.schema_version &&
          email == o.email &&
          status == o.status &&
          sub_status == o.sub_status &&
          action == o.action &&
          domain == o.domain &&
          mx_found == o.mx_found &&
          smtp_check == o.smtp_check &&
          disposable == o.disposable &&
          role_account == o.role_account &&
          free_provider == o.free_provider &&
          suppression_match == o.suppression_match
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [schema_version, email, status, sub_status, action, domain, mx_found, smtp_check, disposable, role_account, free_provider, suppression_match].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
