=begin
#MailOdds Email Validation API

#MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

The version of the OpenAPI document: 1.0.0
Contact: support@mailodds.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Mailodds
  # Flat validation response. Conditional fields are omitted (not null) when not applicable.
  class ValidationResponse < ApiModelBase
    attr_accessor :schema_version

    # Unique request identifier
    attr_accessor :request_id

    attr_accessor :email

    # Validation status
    attr_accessor :status

    # Recommended action
    attr_accessor :action

    # Detailed status reason. Omitted when none.
    attr_accessor :sub_status

    attr_accessor :domain

    # Whether MX records were found for the domain
    attr_accessor :mx_found

    # Primary MX hostname. Omitted when MX not resolved.
    attr_accessor :mx_host

    # Whether SMTP verification passed. Omitted when SMTP not checked.
    attr_accessor :smtp_check

    # Whether domain is catch-all. Omitted when SMTP not checked.
    attr_accessor :catch_all

    # Whether domain is a known disposable email provider
    attr_accessor :disposable

    # Whether address is a role account (e.g., info@, admin@)
    attr_accessor :role_account

    # Whether domain is a known free email provider (e.g., gmail.com)
    attr_accessor :free_provider

    # Validation depth used for this check
    attr_accessor :depth

    # ISO 8601 timestamp of validation
    attr_accessor :processed_at

    # Typo correction suggestion. Omitted when no typo detected.
    attr_accessor :suggested_email

    # Suggested retry delay in milliseconds. Present only for retry_later action.
    attr_accessor :retry_after_ms

    # Whether the domain has an SPF record. Omitted for standard depth.
    attr_accessor :has_spf

    # Whether the domain has a DMARC record. Omitted for standard depth.
    attr_accessor :has_dmarc

    # The domain's DMARC policy. Omitted when no DMARC record found.
    attr_accessor :dmarc_policy

    # Whether the domain's MX IP is on a DNS blocklist (Spamhaus ZEN). Omitted for standard depth.
    attr_accessor :dnsbl_listed

    attr_accessor :suppression_match

    attr_accessor :policy_applied

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'schema_version' => :'schema_version',
        :'request_id' => :'request_id',
        :'email' => :'email',
        :'status' => :'status',
        :'action' => :'action',
        :'sub_status' => :'sub_status',
        :'domain' => :'domain',
        :'mx_found' => :'mx_found',
        :'mx_host' => :'mx_host',
        :'smtp_check' => :'smtp_check',
        :'catch_all' => :'catch_all',
        :'disposable' => :'disposable',
        :'role_account' => :'role_account',
        :'free_provider' => :'free_provider',
        :'depth' => :'depth',
        :'processed_at' => :'processed_at',
        :'suggested_email' => :'suggested_email',
        :'retry_after_ms' => :'retry_after_ms',
        :'has_spf' => :'has_spf',
        :'has_dmarc' => :'has_dmarc',
        :'dmarc_policy' => :'dmarc_policy',
        :'dnsbl_listed' => :'dnsbl_listed',
        :'suppression_match' => :'suppression_match',
        :'policy_applied' => :'policy_applied'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'schema_version' => :'String',
        :'request_id' => :'String',
        :'email' => :'String',
        :'status' => :'String',
        :'action' => :'String',
        :'sub_status' => :'String',
        :'domain' => :'String',
        :'mx_found' => :'Boolean',
        :'mx_host' => :'String',
        :'smtp_check' => :'Boolean',
        :'catch_all' => :'Boolean',
        :'disposable' => :'Boolean',
        :'role_account' => :'Boolean',
        :'free_provider' => :'Boolean',
        :'depth' => :'String',
        :'processed_at' => :'Time',
        :'suggested_email' => :'String',
        :'retry_after_ms' => :'Integer',
        :'has_spf' => :'Boolean',
        :'has_dmarc' => :'Boolean',
        :'dmarc_policy' => :'String',
        :'dnsbl_listed' => :'Boolean',
        :'suppression_match' => :'ValidationResponseSuppressionMatch',
        :'policy_applied' => :'ValidationResponsePolicyApplied'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Mailodds::ValidationResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Mailodds::ValidationResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'schema_version')
        self.schema_version = attributes[:'schema_version']
      else
        self.schema_version = nil
      end

      if attributes.key?(:'request_id')
        self.request_id = attributes[:'request_id']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'action')
        self.action = attributes[:'action']
      else
        self.action = nil
      end

      if attributes.key?(:'sub_status')
        self.sub_status = attributes[:'sub_status']
      end

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      else
        self.domain = nil
      end

      if attributes.key?(:'mx_found')
        self.mx_found = attributes[:'mx_found']
      else
        self.mx_found = nil
      end

      if attributes.key?(:'mx_host')
        self.mx_host = attributes[:'mx_host']
      end

      if attributes.key?(:'smtp_check')
        self.smtp_check = attributes[:'smtp_check']
      end

      if attributes.key?(:'catch_all')
        self.catch_all = attributes[:'catch_all']
      end

      if attributes.key?(:'disposable')
        self.disposable = attributes[:'disposable']
      else
        self.disposable = nil
      end

      if attributes.key?(:'role_account')
        self.role_account = attributes[:'role_account']
      else
        self.role_account = nil
      end

      if attributes.key?(:'free_provider')
        self.free_provider = attributes[:'free_provider']
      else
        self.free_provider = nil
      end

      if attributes.key?(:'depth')
        self.depth = attributes[:'depth']
      else
        self.depth = nil
      end

      if attributes.key?(:'processed_at')
        self.processed_at = attributes[:'processed_at']
      else
        self.processed_at = nil
      end

      if attributes.key?(:'suggested_email')
        self.suggested_email = attributes[:'suggested_email']
      end

      if attributes.key?(:'retry_after_ms')
        self.retry_after_ms = attributes[:'retry_after_ms']
      end

      if attributes.key?(:'has_spf')
        self.has_spf = attributes[:'has_spf']
      end

      if attributes.key?(:'has_dmarc')
        self.has_dmarc = attributes[:'has_dmarc']
      end

      if attributes.key?(:'dmarc_policy')
        self.dmarc_policy = attributes[:'dmarc_policy']
      end

      if attributes.key?(:'dnsbl_listed')
        self.dnsbl_listed = attributes[:'dnsbl_listed']
      end

      if attributes.key?(:'suppression_match')
        self.suppression_match = attributes[:'suppression_match']
      end

      if attributes.key?(:'policy_applied')
        self.policy_applied = attributes[:'policy_applied']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @schema_version.nil?
        invalid_properties.push('invalid value for "schema_version", schema_version cannot be nil.')
      end

      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @action.nil?
        invalid_properties.push('invalid value for "action", action cannot be nil.')
      end

      if @domain.nil?
        invalid_properties.push('invalid value for "domain", domain cannot be nil.')
      end

      if @mx_found.nil?
        invalid_properties.push('invalid value for "mx_found", mx_found cannot be nil.')
      end

      if @disposable.nil?
        invalid_properties.push('invalid value for "disposable", disposable cannot be nil.')
      end

      if @role_account.nil?
        invalid_properties.push('invalid value for "role_account", role_account cannot be nil.')
      end

      if @free_provider.nil?
        invalid_properties.push('invalid value for "free_provider", free_provider cannot be nil.')
      end

      if @depth.nil?
        invalid_properties.push('invalid value for "depth", depth cannot be nil.')
      end

      if @processed_at.nil?
        invalid_properties.push('invalid value for "processed_at", processed_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @schema_version.nil?
      return false if @email.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["valid", "invalid", "catch_all", "do_not_mail", "unknown"])
      return false unless status_validator.valid?(@status)
      return false if @action.nil?
      action_validator = EnumAttributeValidator.new('String', ["accept", "accept_with_caution", "reject", "retry_later"])
      return false unless action_validator.valid?(@action)
      sub_status_validator = EnumAttributeValidator.new('String', ["format_invalid", "mx_missing", "mx_timeout", "smtp_unreachable", "smtp_rejected", "disposable", "role_account", "greylisted", "catch_all_detected", "domain_not_found", "suppression_match", "restricted_military", "restricted_sanctioned"])
      return false unless sub_status_validator.valid?(@sub_status)
      return false if @domain.nil?
      return false if @mx_found.nil?
      return false if @disposable.nil?
      return false if @role_account.nil?
      return false if @free_provider.nil?
      return false if @depth.nil?
      depth_validator = EnumAttributeValidator.new('String', ["standard", "enhanced"])
      return false unless depth_validator.valid?(@depth)
      return false if @processed_at.nil?
      dmarc_policy_validator = EnumAttributeValidator.new('String', ["none", "quarantine", "reject"])
      return false unless dmarc_policy_validator.valid?(@dmarc_policy)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] schema_version Value to be assigned
    def schema_version=(schema_version)
      if schema_version.nil?
        fail ArgumentError, 'schema_version cannot be nil'
      end

      @schema_version = schema_version
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.nil?
        fail ArgumentError, 'email cannot be nil'
      end

      @email = email
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["valid", "invalid", "catch_all", "do_not_mail", "unknown"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] action Object to be assigned
    def action=(action)
      validator = EnumAttributeValidator.new('String', ["accept", "accept_with_caution", "reject", "retry_later"])
      unless validator.valid?(action)
        fail ArgumentError, "invalid value for \"action\", must be one of #{validator.allowable_values}."
      end
      @action = action
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sub_status Object to be assigned
    def sub_status=(sub_status)
      validator = EnumAttributeValidator.new('String', ["format_invalid", "mx_missing", "mx_timeout", "smtp_unreachable", "smtp_rejected", "disposable", "role_account", "greylisted", "catch_all_detected", "domain_not_found", "suppression_match", "restricted_military", "restricted_sanctioned"])
      unless validator.valid?(sub_status)
        fail ArgumentError, "invalid value for \"sub_status\", must be one of #{validator.allowable_values}."
      end
      @sub_status = sub_status
    end

    # Custom attribute writer method with validation
    # @param [Object] domain Value to be assigned
    def domain=(domain)
      if domain.nil?
        fail ArgumentError, 'domain cannot be nil'
      end

      @domain = domain
    end

    # Custom attribute writer method with validation
    # @param [Object] mx_found Value to be assigned
    def mx_found=(mx_found)
      if mx_found.nil?
        fail ArgumentError, 'mx_found cannot be nil'
      end

      @mx_found = mx_found
    end

    # Custom attribute writer method with validation
    # @param [Object] disposable Value to be assigned
    def disposable=(disposable)
      if disposable.nil?
        fail ArgumentError, 'disposable cannot be nil'
      end

      @disposable = disposable
    end

    # Custom attribute writer method with validation
    # @param [Object] role_account Value to be assigned
    def role_account=(role_account)
      if role_account.nil?
        fail ArgumentError, 'role_account cannot be nil'
      end

      @role_account = role_account
    end

    # Custom attribute writer method with validation
    # @param [Object] free_provider Value to be assigned
    def free_provider=(free_provider)
      if free_provider.nil?
        fail ArgumentError, 'free_provider cannot be nil'
      end

      @free_provider = free_provider
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] depth Object to be assigned
    def depth=(depth)
      validator = EnumAttributeValidator.new('String', ["standard", "enhanced"])
      unless validator.valid?(depth)
        fail ArgumentError, "invalid value for \"depth\", must be one of #{validator.allowable_values}."
      end
      @depth = depth
    end

    # Custom attribute writer method with validation
    # @param [Object] processed_at Value to be assigned
    def processed_at=(processed_at)
      if processed_at.nil?
        fail ArgumentError, 'processed_at cannot be nil'
      end

      @processed_at = processed_at
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] dmarc_policy Object to be assigned
    def dmarc_policy=(dmarc_policy)
      validator = EnumAttributeValidator.new('String', ["none", "quarantine", "reject"])
      unless validator.valid?(dmarc_policy)
        fail ArgumentError, "invalid value for \"dmarc_policy\", must be one of #{validator.allowable_values}."
      end
      @dmarc_policy = dmarc_policy
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          schema_version == o.schema_version &&
          request_id == o.request_id &&
          email == o.email &&
          status == o.status &&
          action == o.action &&
          sub_status == o.sub_status &&
          domain == o.domain &&
          mx_found == o.mx_found &&
          mx_host == o.mx_host &&
          smtp_check == o.smtp_check &&
          catch_all == o.catch_all &&
          disposable == o.disposable &&
          role_account == o.role_account &&
          free_provider == o.free_provider &&
          depth == o.depth &&
          processed_at == o.processed_at &&
          suggested_email == o.suggested_email &&
          retry_after_ms == o.retry_after_ms &&
          has_spf == o.has_spf &&
          has_dmarc == o.has_dmarc &&
          dmarc_policy == o.dmarc_policy &&
          dnsbl_listed == o.dnsbl_listed &&
          suppression_match == o.suppression_match &&
          policy_applied == o.policy_applied
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [schema_version, request_id, email, status, action, sub_status, domain, mx_found, mx_host, smtp_check, catch_all, disposable, role_account, free_provider, depth, processed_at, suggested_email, retry_after_ms, has_spf, has_dmarc, dmarc_policy, dnsbl_listed, suppression_match, policy_applied].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
